### ISSUE TITLE
Mask pattern doesn't prevent wrong input type

### ISSUE THREAD

**Issue by vinicarra** [renato-bohler/redux-form-input-masks#45] opened 2018-06-27 13:25 UTC
### What are you reporting?

* [x] Bug
* [ ] Feature request
* [ ] Code refactor
* [ ] Continuous Integration (CI) improvement
* [ ] Changes in documentation (docs)
* [ ] Other (describe)

### What is the current behavior?

I'm using React Native with Redux + Redux Forms and this package to create my forms. I created a date field using the pattern: '99/99/9999', and it works BUT doesn't prevent the user to type letters. I only show the numeric keyboard in this field but the user may copy & paste some text. Even though I'm using a check to see if it's a real date would be very nice if the mask prevented the incorrect inputs.

### What is the expected behavior?

The field should prevent wrong input characters.

### What's your environment?

Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.11.3
  Yarn: Not Found
  npm: 5.6.0
  Watchman: Not Found
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

**Comment by renato-bohler** [comment] 2018-06-27 13:40
Are you using `createTextMask` to achieve this? Can you post some code to help me understand what's going on?

I couldn't reproduce this using the "Build your own" section on the [text mask documentation page](https://renato-bohler.github.io/redux-form-input-masks/#/text-mask). I've simply put `99/99/9999` as the pattern and it does prevent the user from inputting letters or any other non-numeric character.

**Comment by vinicarra** [comment] 2018-06-27 13:47
![captura de tela 2018-06-27 as 10 43 58](https://user-images.githubusercontent.com/21029352/41978046-4dc3e4cc-79f7-11e8-8d62-745f5b50f037.png)
![captura de tela 2018-06-27 as 10 44 07](https://user-images.githubusercontent.com/21029352/41978044-4da21f9a-79f7-11e8-973b-90a0a3e36c65.png)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/21029352/41978108-76f2159e-79f7-11e8-9e12-5118d6b78d11.gif)

**Comment by renato-bohler** [comment] 2018-06-27 13:54
Hmm, this is strange, I'm not able to reproduce this on the documentations on my desktop.

What version of `redux`, `react-redux` and `redux-form` are you using?

I'm not sure if this is related to using `react-native`, I'll have to test.

**Comment by vinicarra** [comment] 2018-06-27 14:01
- "redux": "^4.0.0"
- "redux-form": "^7.4.2"
- "redux-form-input-masks": "^1.1.5"
- "react-redux": "^5.0.7"

**Comment by vinicarra** [comment] 2018-06-30 22:34
I've found myself having more problems than solutions by using this package. Although it works gracefully for web React applications it doesn't provide me the same results in mobile apps with RN. As you suggested this may be React Native issues but would be really nice if you could make it work for mobile as well. In android the field couldn't ever be sucessfully valitaded leading to some major problems with my form so I just gave up using this (I know it's not your fault at ALL), for now I'm using react forms normalize to handle my needs.

**Comment by renato-bohler** [comment] 2018-06-30 23:38
I haven't really tested this library with `react-native`. I wasn't expecting that it would have any issues, since it's only using `redux-form` API.

I will be able to give all those open issues some attention in the next week or two, including yours.

Thanks for the feedback anyways.

**Comment by renato-bohler** [comment] 2018-07-21 02:04
I finally managed to test this library with `react-native` and, unfortunately, it is far from being able to support it. A lot of refactor and testing would be required in order to achieve this compability, and I'm not even sure if that would be possible (managing the caret position on `react-native`'s inputs seems to be one of the biggest problems).

I'm closing this by now, but we should at least document this downside.

**Closed by renato-bohler** 2018-07-21 02:04 UTC
