### ISSUE TITLE
Unrecognised `format` prop

### ISSUE THREAD

**Issue by rdourado** [renato-bohler/redux-form-input-masks#98] opened 2019-12-06 14:58 UTC
### What are you reporting?

* [x] Bug
* [ ] Feature request
* [ ] Code refactor
* [ ] Continuous Integration (CI) improvement
* [ ] Changes in documentation (docs)
* [ ] Other (describe)

### What is the current behavior?

React is not recognising `format` prop and is throwing a warning.

### What is the expected behavior?

Get along with React and avoid any warnings.

### What's your environment?

```
{
	"react": "^16.12.0",
	"react-dom": "^16.12.0",
	"react-redux": "^7.1.3",
	"redux": "^4.0.4",
	"redux-form": "^8.2.6",
	"redux-form-input-masks": "^2.0.1",
}
```

### Other information

The following warning is being shown: 
```
Warning: Invalid value for prop `format` on <input> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://fb.me/react-attribute-behavior
```

**Comment by renato-bohler** [comment] 2019-12-06 18:11
Hey @rdourado. I was unable to reproduce this problem. On this [sandbox](https://codesandbox.io/s/keen-wescoff-8ow06), I'm using the exact same dependency versions and the `"input"` component.

The problem must be with the component that you are connecting to `redux-form` itself, as it may be forwarding unnecessary props to its children.

To help you, I would need more information and probably a sandbox. You can fork the sandbox I created.

I'm closing this for now, because it doesn't seem a problem with the library. Feel free to comment or reopen this issue.

**Closed by renato-bohler** 2019-12-06 18:11 UTC

**Comment by rdourado** [comment] 2019-12-06 18:57
@renato-bohler You were right. I was spreading it on my custom input component instead of redux-form's Field component. My mistake. =)
